clear cache
FakeNewsChallenge/fnc-1-baseline pull request #8
Opened 2017-03-02 20:59 UTC by borisnadion

2017-03-02 22:34 UTC, delip commented on utils/system.py
> +def parse_params():
This is a non-standard way of handling cmd line args. Mind using argparse? 
https://docs.python.org/2/library/argparse.html

2017-03-03 19:33 UTC, delip requested changes

2017-03-03 19:33 UTC, delip commented on requirements.txt
> +argparse
argparse is part of standard python library. no need to add to requirements.

2017-03-03 19:33 UTC, delip commented on utils/system.py
> +    parser.add_argument('-d', '--dry-run', action='store_true', default=False, help="don't actually clean cache files")
pls remove --dry-run. It's not like we're launching a missile 😉

2017-03-03 19:33 UTC, delip requested changes

2017-03-03 19:33 UTC, delip commented on utils/system.py
> +    sys.exit(0)
why sys.exit(0) if --clean-cache is provided?

Shouldn't it clean the cache and continue with training by rebuilding the feature files?

2017-03-14 22:08 UTC, delip commented on utils/system.py
> +# supposed to work on windows
pls remove this comment

2017-03-14 22:09 UTC, delip approved these changes
Looks good. Pls remove that comment before merging.

2017-03-16 08:52 UTC, borisnadion commented on utils/system.py
> +# supposed to work on windows
done

2017-03-17 15:08 UTC, j6mes approved these changes
ok

2017-03-17 15:08 UTC, merged